In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [
    'the glass of milk',
    'the cup of tea',
    'you are a good developer',
    'dwag love the high songs',
    'this all is heart settling'
]

In [4]:
sent

['the glass of milk',
 'the cup of tea',
 'you are a good developer',
 'dwag love the high songs',
 'this all is heart settling']

In [5]:
## Definng the vobalulary size
voc_size = 10000

In [ ]:
## one hot representation 
one_hot_rep = [one_hot(words,voc_size)for words in sent]    ## converting the OHE representation
one_hot_rep

[[8111, 3046, 250, 5264],
 [8111, 7421, 250, 8299],
 [2149, 6301, 2298, 3101, 9684],
 [1089, 9939, 8111, 2933, 236],
 [180, 5484, 5771, 6406, 1753]]

In [ ]:
## word embedding representation
from tensorflow.keras.layers import Embedding      ## converts words into dense vector representations
from tensorflow.keras.utils import pad_sequences   ## to make the length of sentence same
from tensorflow.keras.models import Sequential     ## to create the model
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8111 3046  250 5264]
 [   0    0    0    0 8111 7421  250 8299]
 [   0    0    0 2149 6301 2298 3101 9684]
 [   0    0    0 1089 9939 8111 2933  236]
 [   0    0    0  180 5484 5771 6406 1753]]


In [ ]:
## feature reprenstation 
dim=10      ## dimension of feature vector

In [ ]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))     ## creating the embedding layer
model.compile('adam','mse')

d:\Data Analysis\DeepLearning\DeepLearning_From_Scratch\tfenv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step


array([[[-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.04978765,  0.04585458, -0.01483677, -0.00260331,
         -0.01391337, -0.00200825, -0.02101682,  0.02716816,
         -0.02823789,  0.01067096],
        [ 0.0159423 ,  0.02425082, -0.03663258, -0.01130565,
          0.005913  ,  0.02476021,  0.02595599, -0.00397147,
         -0.0268865 ,  0.00265355],
        [ 0.00038732,  0.01314821,  0.04264721, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 8111, 3046,  250, 5264], dtype=int32)

In [19]:
print(embedded_docs.shape)
print(embedded_docs[0].shape)

(5, 8)
(8,)


In [21]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[[-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.01608263, -0.01997854, -0.02661318,  0.02540078,
         -0.03691411,  0.03388592, -0.02652478, -0.03598896,
          0.0110154 ,  0.01632435],
        [-0.04978765,  0.04585458, -0.01483677, -0.00260331,
         -0.01391337, -0.00200825, -0.02101682,  0.02716816,
         -0.02823789,  0.01067096],
        [ 0.0159423 ,  0.02425082, -0.03663258, -0.01130565,
          0.005913  ,  0.02476021,  0.02595599, -0.00397147,
         -0.0268865 ,  0.00265355],
        [ 0.00038732,  0.01314821,  0.04264721, -0.0